# Generated by Django 6.0 on 2026-04-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='button_choice',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('github', 'Github')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='button_choice_url',
            field=models.URLField(blank=True),
        ),
    ]
