# Generated by Django 6.0 on 2026-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_project_button_choice_project_button_choice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
